package tgb

// Code generated by go-tg/gen. DO NOT EDIT.
//
// Telegram Bot API version: 9.3
// Release date: December 31, 2025
// Spec hash: f010e435c22c

import (
	"context"

	"github.com/mr-linch/go-tg"
)

// BusinessConnectionHandler it's typed handler for [BusinessConnectionUpdate].
// Implements [Handler] interface.
type BusinessConnectionHandler func(context.Context, *BusinessConnectionUpdate) error

func (handler BusinessConnectionHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &BusinessConnectionUpdate{
		BusinessConnection: update.BusinessConnection,
		BaseUpdate:         BaseUpdate{Update: update, Client: update.Client},
	})
}

// CallbackQueryHandler it's typed handler for [CallbackQueryUpdate].
// Implements [Handler] interface.
type CallbackQueryHandler func(context.Context, *CallbackQueryUpdate) error

func (handler CallbackQueryHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &CallbackQueryUpdate{
		CallbackQuery: update.CallbackQuery,
		BaseUpdate:    BaseUpdate{Update: update, Client: update.Client},
	})
}

// ChatBoostHandler it's typed handler for [ChatBoostUpdate].
// Implements [Handler] interface.
type ChatBoostHandler func(context.Context, *ChatBoostUpdate) error

func (handler ChatBoostHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &ChatBoostUpdate{
		ChatBoostUpdated: update.ChatBoost,
		BaseUpdate:       BaseUpdate{Update: update, Client: update.Client},
	})
}

// ChatJoinRequestHandler it's typed handler for [ChatJoinRequestUpdate].
// Implements [Handler] interface.
type ChatJoinRequestHandler func(context.Context, *ChatJoinRequestUpdate) error

func (handler ChatJoinRequestHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &ChatJoinRequestUpdate{
		ChatJoinRequest: update.ChatJoinRequest,
		BaseUpdate:      BaseUpdate{Update: update, Client: update.Client},
	})
}

// ChatMemberUpdatedHandler it's typed handler for [ChatMemberUpdatedUpdate].
// Implements [Handler] interface.
type ChatMemberUpdatedHandler func(context.Context, *ChatMemberUpdatedUpdate) error

func (handler ChatMemberUpdatedHandler) Handle(ctx context.Context, update *Update) error {
	var v *tg.ChatMemberUpdated
	switch {
	case update.MyChatMember != nil:
		v = update.MyChatMember
	case update.ChatMember != nil:
		v = update.ChatMember
	}
	if v != nil {
		return handler(ctx, &ChatMemberUpdatedUpdate{
			ChatMemberUpdated: v,
			BaseUpdate:        BaseUpdate{Update: update, Client: update.Client},
		})
	}
	return nil
}

// ChosenInlineResultHandler it's typed handler for [ChosenInlineResultUpdate].
// Implements [Handler] interface.
type ChosenInlineResultHandler func(context.Context, *ChosenInlineResultUpdate) error

func (handler ChosenInlineResultHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &ChosenInlineResultUpdate{
		ChosenInlineResult: update.ChosenInlineResult,
		BaseUpdate:         BaseUpdate{Update: update, Client: update.Client},
	})
}

// DeletedBusinessMessagesHandler it's typed handler for [DeletedBusinessMessagesUpdate].
// Implements [Handler] interface.
type DeletedBusinessMessagesHandler func(context.Context, *DeletedBusinessMessagesUpdate) error

func (handler DeletedBusinessMessagesHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &DeletedBusinessMessagesUpdate{
		BusinessMessagesDeleted: update.DeletedBusinessMessages,
		BaseUpdate:              BaseUpdate{Update: update, Client: update.Client},
	})
}

// InlineQueryHandler it's typed handler for [InlineQueryUpdate].
// Implements [Handler] interface.
type InlineQueryHandler func(context.Context, *InlineQueryUpdate) error

func (handler InlineQueryHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &InlineQueryUpdate{
		InlineQuery: update.InlineQuery,
		BaseUpdate:  BaseUpdate{Update: update, Client: update.Client},
	})
}

// MessageHandler it's typed handler for [MessageUpdate].
// Implements [Handler] interface.
type MessageHandler func(context.Context, *MessageUpdate) error

func (handler MessageHandler) Handle(ctx context.Context, update *Update) error {
	var v *tg.Message
	switch {
	case update.Message != nil:
		v = update.Message
	case update.EditedMessage != nil:
		v = update.EditedMessage
	case update.ChannelPost != nil:
		v = update.ChannelPost
	case update.EditedChannelPost != nil:
		v = update.EditedChannelPost
	case update.BusinessMessage != nil:
		v = update.BusinessMessage
	case update.EditedBusinessMessage != nil:
		v = update.EditedBusinessMessage
	}
	if v != nil {
		return handler(ctx, &MessageUpdate{
			Message:    v,
			BaseUpdate: BaseUpdate{Update: update, Client: update.Client},
		})
	}
	return nil
}

// MessageReactionCountHandler it's typed handler for [MessageReactionCountUpdate].
// Implements [Handler] interface.
type MessageReactionCountHandler func(context.Context, *MessageReactionCountUpdate) error

func (handler MessageReactionCountHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &MessageReactionCountUpdate{
		MessageReactionCountUpdated: update.MessageReactionCount,
		BaseUpdate:                  BaseUpdate{Update: update, Client: update.Client},
	})
}

// MessageReactionHandler it's typed handler for [MessageReactionUpdate].
// Implements [Handler] interface.
type MessageReactionHandler func(context.Context, *MessageReactionUpdate) error

func (handler MessageReactionHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &MessageReactionUpdate{
		MessageReactionUpdated: update.MessageReaction,
		BaseUpdate:             BaseUpdate{Update: update, Client: update.Client},
	})
}

// PollAnswerHandler it's typed handler for [PollAnswerUpdate].
// Implements [Handler] interface.
type PollAnswerHandler func(context.Context, *PollAnswerUpdate) error

func (handler PollAnswerHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &PollAnswerUpdate{
		PollAnswer: update.PollAnswer,
		BaseUpdate: BaseUpdate{Update: update, Client: update.Client},
	})
}

// PollHandler it's typed handler for [PollUpdate].
// Implements [Handler] interface.
type PollHandler func(context.Context, *PollUpdate) error

func (handler PollHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &PollUpdate{
		Poll:       update.Poll,
		BaseUpdate: BaseUpdate{Update: update, Client: update.Client},
	})
}

// PreCheckoutQueryHandler it's typed handler for [PreCheckoutQueryUpdate].
// Implements [Handler] interface.
type PreCheckoutQueryHandler func(context.Context, *PreCheckoutQueryUpdate) error

func (handler PreCheckoutQueryHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &PreCheckoutQueryUpdate{
		PreCheckoutQuery: update.PreCheckoutQuery,
		BaseUpdate:       BaseUpdate{Update: update, Client: update.Client},
	})
}

// PurchasedPaidMediaHandler it's typed handler for [PurchasedPaidMediaUpdate].
// Implements [Handler] interface.
type PurchasedPaidMediaHandler func(context.Context, *PurchasedPaidMediaUpdate) error

func (handler PurchasedPaidMediaHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &PurchasedPaidMediaUpdate{
		PaidMediaPurchased: update.PurchasedPaidMedia,
		BaseUpdate:         BaseUpdate{Update: update, Client: update.Client},
	})
}

// RemovedChatBoostHandler it's typed handler for [RemovedChatBoostUpdate].
// Implements [Handler] interface.
type RemovedChatBoostHandler func(context.Context, *RemovedChatBoostUpdate) error

func (handler RemovedChatBoostHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &RemovedChatBoostUpdate{
		ChatBoostRemoved: update.RemovedChatBoost,
		BaseUpdate:       BaseUpdate{Update: update, Client: update.Client},
	})
}

// ShippingQueryHandler it's typed handler for [ShippingQueryUpdate].
// Implements [Handler] interface.
type ShippingQueryHandler func(context.Context, *ShippingQueryUpdate) error

func (handler ShippingQueryHandler) Handle(ctx context.Context, update *Update) error {
	return handler(ctx, &ShippingQueryUpdate{
		ShippingQuery: update.ShippingQuery,
		BaseUpdate:    BaseUpdate{Update: update, Client: update.Client},
	})
}
