package tgb

// Code generated by go-tg/gen. DO NOT EDIT.
//
// Telegram Bot API version: 9.3
// Release date: December 31, 2025
// Spec hash: 64aa94655be4

import "github.com/mr-linch/go-tg"

// Message register handlers for Update with not empty Message field.
func (bot *Router) Message(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeMessage, handler, filters...)
}

// EditedMessage register handlers for Update with not empty EditedMessage field.
func (bot *Router) EditedMessage(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeEditedMessage, handler, filters...)
}

// ChannelPost register handlers for Update with not empty ChannelPost field.
func (bot *Router) ChannelPost(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeChannelPost, handler, filters...)
}

// EditedChannelPost register handlers for Update with not empty EditedChannelPost field.
func (bot *Router) EditedChannelPost(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeEditedChannelPost, handler, filters...)
}

// BusinessConnection register handlers for Update with not empty BusinessConnection field.
func (bot *Router) BusinessConnection(handler BusinessConnectionHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeBusinessConnection, handler, filters...)
}

// BusinessMessage register handlers for Update with not empty BusinessMessage field.
func (bot *Router) BusinessMessage(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeBusinessMessage, handler, filters...)
}

// EditedBusinessMessage register handlers for Update with not empty EditedBusinessMessage field.
func (bot *Router) EditedBusinessMessage(handler MessageHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeEditedBusinessMessage, handler, filters...)
}

// DeletedBusinessMessages register handlers for Update with not empty DeletedBusinessMessages field.
func (bot *Router) DeletedBusinessMessages(handler DeletedBusinessMessagesHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeDeletedBusinessMessages, handler, filters...)
}

// MessageReaction register handlers for Update with not empty MessageReaction field.
func (bot *Router) MessageReaction(handler MessageReactionHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeMessageReaction, handler, filters...)
}

// MessageReactionCount register handlers for Update with not empty MessageReactionCount field.
func (bot *Router) MessageReactionCount(handler MessageReactionCountHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeMessageReactionCount, handler, filters...)
}

// InlineQuery register handlers for Update with not empty InlineQuery field.
func (bot *Router) InlineQuery(handler InlineQueryHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeInlineQuery, handler, filters...)
}

// ChosenInlineResult register handlers for Update with not empty ChosenInlineResult field.
func (bot *Router) ChosenInlineResult(handler ChosenInlineResultHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeChosenInlineResult, handler, filters...)
}

// CallbackQuery register handlers for Update with not empty CallbackQuery field.
func (bot *Router) CallbackQuery(handler CallbackQueryHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeCallbackQuery, handler, filters...)
}

// ShippingQuery register handlers for Update with not empty ShippingQuery field.
func (bot *Router) ShippingQuery(handler ShippingQueryHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeShippingQuery, handler, filters...)
}

// PreCheckoutQuery register handlers for Update with not empty PreCheckoutQuery field.
func (bot *Router) PreCheckoutQuery(handler PreCheckoutQueryHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypePreCheckoutQuery, handler, filters...)
}

// PurchasedPaidMedia register handlers for Update with not empty PurchasedPaidMedia field.
func (bot *Router) PurchasedPaidMedia(handler PurchasedPaidMediaHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypePurchasedPaidMedia, handler, filters...)
}

// Poll register handlers for Update with not empty Poll field.
func (bot *Router) Poll(handler PollHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypePoll, handler, filters...)
}

// PollAnswer register handlers for Update with not empty PollAnswer field.
func (bot *Router) PollAnswer(handler PollAnswerHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypePollAnswer, handler, filters...)
}

// MyChatMember register handlers for Update with not empty MyChatMember field.
func (bot *Router) MyChatMember(handler ChatMemberUpdatedHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeMyChatMember, handler, filters...)
}

// ChatMember register handlers for Update with not empty ChatMember field.
func (bot *Router) ChatMember(handler ChatMemberUpdatedHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeChatMember, handler, filters...)
}

// ChatJoinRequest register handlers for Update with not empty ChatJoinRequest field.
func (bot *Router) ChatJoinRequest(handler ChatJoinRequestHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeChatJoinRequest, handler, filters...)
}

// ChatBoost register handlers for Update with not empty ChatBoost field.
func (bot *Router) ChatBoost(handler ChatBoostHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeChatBoost, handler, filters...)
}

// RemovedChatBoost register handlers for Update with not empty RemovedChatBoost field.
func (bot *Router) RemovedChatBoost(handler RemovedChatBoostHandler, filters ...Filter) *Router {
	return bot.register(tg.UpdateTypeRemovedChatBoost, handler, filters...)
}
