package tgb

// Code generated by go-tg/gen. DO NOT EDIT.
//
// Telegram Bot API version: 9.3
// Release date: December 31, 2025
// Spec hash: 64aa94655be4

import "github.com/mr-linch/go-tg"

// BaseUpdate contains common fields for all typed update wrappers.
type BaseUpdate struct {
	Update *Update
	Client *tg.Client
}

// MessageReactionUpdate it's extend wrapper around [tg.MessageReactionUpdated].
type MessageReactionUpdate struct {
	*tg.MessageReactionUpdated
	BaseUpdate
}

// ShippingQueryUpdate it's extend wrapper around [tg.ShippingQuery].
type ShippingQueryUpdate struct {
	*tg.ShippingQuery
	BaseUpdate
}

// PreCheckoutQueryUpdate it's extend wrapper around [tg.PreCheckoutQuery].
type PreCheckoutQueryUpdate struct {
	*tg.PreCheckoutQuery
	BaseUpdate
}

// RemovedChatBoostUpdate it's extend wrapper around [tg.ChatBoostRemoved].
type RemovedChatBoostUpdate struct {
	*tg.ChatBoostRemoved
	BaseUpdate
}

// MessageUpdate it's extend wrapper around [tg.Message].
type MessageUpdate struct {
	*tg.Message
	BaseUpdate
}

// DeletedBusinessMessagesUpdate it's extend wrapper around [tg.BusinessMessagesDeleted].
type DeletedBusinessMessagesUpdate struct {
	*tg.BusinessMessagesDeleted
	BaseUpdate
}

// InlineQueryUpdate it's extend wrapper around [tg.InlineQuery].
type InlineQueryUpdate struct {
	*tg.InlineQuery
	BaseUpdate
}

// ChosenInlineResultUpdate it's extend wrapper around [tg.ChosenInlineResult].
type ChosenInlineResultUpdate struct {
	*tg.ChosenInlineResult
	BaseUpdate
}

// CallbackQueryUpdate it's extend wrapper around [tg.CallbackQuery].
type CallbackQueryUpdate struct {
	*tg.CallbackQuery
	BaseUpdate
}

// PollUpdate it's extend wrapper around [tg.Poll].
type PollUpdate struct {
	*tg.Poll
	BaseUpdate
}

// PollAnswerUpdate it's extend wrapper around [tg.PollAnswer].
type PollAnswerUpdate struct {
	*tg.PollAnswer
	BaseUpdate
}

// ChatMemberUpdatedUpdate it's extend wrapper around [tg.ChatMemberUpdated].
type ChatMemberUpdatedUpdate struct {
	*tg.ChatMemberUpdated
	BaseUpdate
}

// ChatBoostUpdate it's extend wrapper around [tg.ChatBoostUpdated].
type ChatBoostUpdate struct {
	*tg.ChatBoostUpdated
	BaseUpdate
}

// BusinessConnectionUpdate it's extend wrapper around [tg.BusinessConnection].
type BusinessConnectionUpdate struct {
	*tg.BusinessConnection
	BaseUpdate
}

// MessageReactionCountUpdate it's extend wrapper around [tg.MessageReactionCountUpdated].
type MessageReactionCountUpdate struct {
	*tg.MessageReactionCountUpdated
	BaseUpdate
}

// PurchasedPaidMediaUpdate it's extend wrapper around [tg.PaidMediaPurchased].
type PurchasedPaidMediaUpdate struct {
	*tg.PaidMediaPurchased
	BaseUpdate
}

// ChatJoinRequestUpdate it's extend wrapper around [tg.ChatJoinRequest].
type ChatJoinRequestUpdate struct {
	*tg.ChatJoinRequest
	BaseUpdate
}
